### ISSUE TITLE
Not able to run it

### ISSUE THREAD

**Issue by WhiteHatArpit** [teesloane/sniptor#8]
I am not able to run it with `npm start` after doing `npm install`.
Building doesn't help either. Also, your package.json looks for main.js which is present not in app but src directory.
I am on Linux.

**Comment by teesloane** [comment]
Hi TigerApps,

Thanks for letting us know! We will take a look at this shortly. Does the build from the release page work on your machine?

**Comment by WhiteHatArpit** [comment]
Release page? Where?
I cloned the master branch.

**Comment by teesloane** [comment]
I think we might need to update some dependencies perhaps.

As for release pages - Github has a tab for release candidates of your commits. This is where we'll be uploading our updates of the app. Here's a screenshot:

![screenshot 2016-02-26 16 03 08](https://cloud.githubusercontent.com/assets/12987958/13365367/97cfbb44-dca2-11e5-9e3d-874d5ce36811.png)

**Comment by WhiteHatArpit** [comment]
Thanks! Yes, figured it out. This one (from latest release) runs fine.
Running from the code, just gives a white window.

**Comment by teesloane** [comment]
Excellent! Thanks for the heads up on the bug. We'll look into it.

**Comment by WhiteHatArpit** [comment]
![screenshot from 2016-02-27 02 42 13](https://cloud.githubusercontent.com/assets/7329865/13365589/e785bc52-dcfb-11e5-816f-2cb3b2f06c46.png)
App directory inside the release. 
Comparing it to the repo, I think I am missing something to get files from src to app.

**Comment by broneks** [comment]
@TigerApps I'll look into this issue on my Linux computer.

**Comment by broneks** [comment]
@TigerApps 
Did you run "gulp compile" after you ran "npm install"? That's what will compile the src files into the app directory and create "app/main.js".

We'll make sure to add a section to the README to explain how to properly get started with the project for people looking to contribute.

**Comment by WhiteHatArpit** [comment]
I guess that will be it. I didn't use `gulp compile`.
Thanks for the good work!

On other note, do you have any to-do list for the project?

**Comment by broneks** [comment]
@TigerApps 
Not currently, but we would welcome ideas or PRs.

One thing that we really need to do is to add some unit tests (using Jasmine).
